### ISSUE TITLE
Bugs when match regex with alternation

### ISSUE THREAD

**Issue by l1nknyto** [IonicaBizau/match-all#12]
let s = "Hello World and Mars";
console.log(matchAll(s, /(World)|(Mars)/gi).toArray());
// => [ "World"]

here's my fix
```
        , next: function next() {
            var c = this.nextRaw();
            if (c) {
              for (var i = 1; i < c.length; i++) {
                if (c[i]) return c[i];
              }
            } else return null;
        }
```

let s = "Hello World and Mars";
console.log(matchAll(s, /(World)|(Mars)/gi).toArray());
// => [ "World", "Mars" ]

Hope you could update yours
Thanks

**Comment by IonicaBizau** [comment]
Oh, I agree! Thanks for this!

Can you please submit a PR with this change? 🚀

**Comment by l1nknyto** [comment]
done
