### ISSUE TITLE
Use a real Iterator?

### ISSUE THREAD

**Issue by hyvyys** [IonicaBizau/match-all#19]
Could it be possible to make this library into a real `String.matchAll` polyfill? I.e. return a real `Iterator` object that can be fed to `Array.from` method etc. So that we get a full object representation of all the matches and not just the whole matches as from `toArray`.

**Comment by IonicaBizau** [comment]
Can you add an example of the API you would like? Thanks!

**Comment by hyvyys** [comment]
My apologies, there already is an official polyfill, I don't know how I missed it. I suspect I was misled by its only second position in Google results, after your package, even though it has 20 times the downloads.
https://www.npmjs.com/package/string.prototype.matchall
